// Enhanced Chatbot Service with Comprehensive Agricultural Knowledge
export const enhancedChatService = {
  sendMessage: async (message: string, language: 'en' | 'hi' | 'mr' | 'gu' | 'pa' | 'bn' | 'ta' | 'te' = 'en'): Promise<string> => {
    await new Promise(resolve => setTimeout(resolve, 800));
    
    // Advanced AI-like chatbot with context-aware responses
    const lowerMessage = message.toLowerCase();
    
    // Comprehensive keyword matching function
    const matchesKeyword = (keywords: string[]): boolean => {
      return keywords.some(keyword => lowerMessage.includes(keyword.toLowerCase()));
    };
    
    // English responses with extensive agricultural knowledge
    if (language === 'en') {
      // Greetings
      if (matchesKeyword(['hello', 'hi', 'hey', 'namaste', 'namaskar'])) {
        return "👋 Namaste! I'm your KisanConnect AI Assistant. I'm here to help you with:\n\n✅ Crop cultivation guidance\n✅ Pest & disease management\n✅ Soil & fertilizer advice\n✅ Weather & irrigation tips\n✅ Market prices & trends\n✅ Government schemes\n\nWhat would you like to know about farming today?";
      }
      
      // Help requests
      if (matchesKeyword(['help', 'guide', 'assist', 'what can you do'])) {
        return "🤝 **How I Can Help You:**\n\n**Ask me about:**\n• Specific crops (wheat, rice, cotton, etc.)\n• Soil testing & management\n• Fertilizers & organic farming\n• Pest & disease control\n• Irrigation techniques\n• Market prices & selling tips\n• Weather-based farming\n• Government schemes & subsidies\n• Crop rotation & seasonal planning\n\n**Example Questions:**\n• \"How to grow wheat?\"\n• \"What fertilizer for rice?\"\n• \"Best time to sow cotton?\"\n• \"Current tomato prices?\"\n• \"How to control pests organically?\"\n\nI respond in multiple Indian languages! 🇮🇳";
      }
      
      // Thanks
      if (matchesKeyword(['thank', 'thanks', 'appreciate'])) {
        return "🙏 You're very welcome! I'm always here to help. Remember:\n\n💡 Check our **Weather Widget** for forecasts\n📊 Visit **Market Analysis** for prices\n🌾 Use **Crop Recommendation** for personalized suggestions\n📸 Try **Disease Detection** to identify plant problems\n\nHappy farming! May your fields be fertile and your harvests abundant! 🌾✨";
      }
      
      // Wheat cultivation
      if (matchesKeyword(['wheat', 'gehu', 'gahu'])) {
        return "🌾 **Wheat Cultivation Guide:**\n\n📅 **Sowing Time:** November-December (Rabi season)\n🌡️ **Temperature:** 10-25°C optimal\n💧 **Irrigation:** Every 20-25 days, 4-6 irrigations needed\n🧪 **Soil pH:** 6.0-7.5 (slightly acidic to neutral)\n🌱 **Seed Rate:** 100-125 kg/hectare\n🌿 **Varieties:** HD-2967, PBW-343, DBW-17\n💰 **Expected Yield:** 40-50 quintals/hectare\n\n**Pro Tips:**\n• Apply urea in 3 splits for better nitrogen use\n• Control weeds at 30-35 days after sowing\n• Watch for rust and aphid attacks\n• First irrigation at 20-25 days after sowing";
      }
      
      // Rice cultivation
      if (matchesKeyword(['rice', 'paddy', 'dhan', 'chawal'])) {
        return "🌾 **Rice Cultivation Complete Guide:**\n\n📅 **Seasons:**\n• Kharif (June-July) - Main season\n• Rabi (November-December) - Winter rice\n🌡️ **Temperature:** 20-35°C\n💧 **Water:** Needs standing water, 1200-1500mm rainfall\n🧪 **Soil pH:** 5.5-6.5 (acidic)\n🌱 **Varieties:** Swarna, IR-64, Basmati\n💰 **Yield:** 50-60 quintals/hectare\n\n**Key Points:**\n• Puddling essential for water retention\n• Transplant 25-30 day old seedlings\n• Apply zinc sulfate if leaves turn yellow\n• Beware of blast, brown spot diseases\n• Maintain 2-3 inches of standing water";
      }
      
      // Cotton
      if (matchesKeyword(['cotton', 'kapas', 'rui'])) {
        return "🌿 **Cotton Farming Essentials:**\n\n📅 **Sowing:** April-May (Kharif)\n🌡️ **Climate:** Warm 21-30°C, 180+ frost-free days\n💧 **Rainfall:** 50-100cm annually\n🧪 **Soil:** Black cotton soil ideal (pH 6.5-8.0)\n🌱 **Spacing:** 90cm x 60cm\n💰 **Yield:** 15-20 quintals/hectare\n\n**Management:**\n• Drip irrigation saves 40% water\n• Pink bollworm is major pest - use pheromone traps\n• Bt cotton provides bollworm resistance\n• Harvest when 60% bolls open\n• First picking after 120-130 days";
      }
      
      // Sugarcane
      if (matchesKeyword(['sugarcane', 'ganna', 'sugar cane'])) {
        return "🎋 **Sugarcane Cultivation:**\n\n📅 **Planting:** February-March (Spring), September-October (Autumn)\n🌡️ **Temperature:** 20-30°C during growth\n💧 **Water:** High requirement - 1500-2500mm\n🧪 **Soil:** Deep, well-drained loam (pH 6.5-7.5)\n🌱 **Varieties:** Co-0238, Co-86032, Co-0403\n💰 **Yield:** 800-1000 quintals/hectare\n\n**Care Tips:**\n• Apply 300kg N, 60kg P, 60kg K per hectare\n• Earthing up at 90-120 days critical\n• Control red rot and smut diseases\n• Harvest at 10-12 months\n• Ratoon crop possible for 2-3 seasons";
      }
      
      // Maize/Corn
      if (matchesKeyword(['maize', 'corn', 'makka', 'bhutta'])) {
        return "🌽 **Maize/Corn Growing Guide:**\n\n📅 **Season:** Kharif (June-July), Rabi (October-November)\n🌡️ **Temperature:** 21-27°C ideal\n💧 **Irrigation:** Critical at tasseling and grain filling\n🧪 **Soil pH:** 5.5-7.5\n🌱 **Spacing:** 60cm x 20cm\n💰 **Yield:** 60-70 quintals/hectare\n\n**Best Practices:**\n• Use hybrid seeds for better yield\n• Apply 120kg N in 3 splits\n• Control fall armyworm with biological agents\n• Harvest when kernels harden\n• Proper drying essential to prevent mold";
      }
      
      // Soybean
      if (matchesKeyword(['soybean', 'soya', 'soy bean'])) {
        return "🫘 **Soybean Farming Tips:**\n\n📅 **Sowing:** June-July (with monsoon)\n🌡️ **Temperature:** 20-30°C\n💧 **Rainfall:** 450-700mm\n🧪 **Soil:** Well-drained loam (pH 6.5-7.5)\n🌱 **Seed Rate:** 75-80 kg/hectare\n💰 **Yield:** 20-25 quintals/hectare\n\n**Success Tips:**\n• Inoculate seeds with Rhizobium bacteria\n• Sow at 30-45cm row spacing\n• Control yellow mosaic virus (use resistant varieties)\n• Harvest when 95% pods turn brown\n• Good rotation crop - adds nitrogen to soil";
      }
      
      // Groundnut/Peanut
      if (matchesKeyword(['groundnut', 'peanut', 'mungfali', 'singdana'])) {
        return "🥜 **Groundnut/Peanut Cultivation:**\n\n📅 **Season:** Kharif (June) & Summer (January-February)\n🌡️ **Temperature:** 20-30°C\n💧 **Water:** 500-600mm well distributed\n🧪 **Soil:** Sandy loam, red soil (pH 6.0-6.5)\n🌱 **Varieties:** TMV-2, JL-24, TAG-24\n💰 **Yield:** 20-25 quintals/hectare\n\n**Pro Tips:**\n• Apply gypsum at flowering (200-400 kg/ha)\n• Critical for pod development\n• Control leaf miner and tikka disease\n• Harvest when leaves turn yellow\n• Cure pods in sun for 3-4 days before storage";
      }
      
      // Soil management
      if (matchesKeyword(['soil', 'mitti', 'land', 'ground'])) {
        return "🌱 **Soil Health Management:**\n\n**Soil Testing:** Test every 2-3 years for NPK, pH, organic matter\n\n**Soil Types & Best Crops:**\n• **Black Soil:** Cotton, soybean, wheat, jowar\n• **Red Soil:** Groundnut, millets, pulses\n• **Alluvial:** Rice, wheat, sugarcane, vegetables\n• **Sandy:** Bajra, groundnut, watermelon\n• **Laterite:** Cashew, coconut, spices\n\n**Improvement Methods:**\n• Add organic matter (FYM 10-15 tons/ha)\n• Green manuring with dhaincha, sunhemp\n• Crop rotation to prevent nutrient depletion\n• Mulching to retain moisture\n• Avoid excessive tilling";
      }
      
      // Fertilizer
      if (matchesKeyword(['fertilizer', 'fertiliser', 'khad', 'urvar', 'npk', 'urea'])) {
        return "💊 **Fertilizer Application Guide:**\n\n**Major Nutrients (NPK):**\n• **Nitrogen (N):** Leaf growth, greening - Urea, CAN\n• **Phosphorus (P):** Root development - DAP, SSP\n• **Potassium (K):** Disease resistance - MOP, SOP\n\n**Micro-nutrients:**\n• **Zinc:** Prevents yellow leaves, stunted growth\n• **Boron:** Essential for flowering, fruit set\n• **Iron:** Prevents chlorosis in young leaves\n\n**Organic Options:**\n• Farmyard manure (FYM): 10-15 tons/hectare\n• Vermicompost: 2-3 tons/hectare\n• Neem cake: Pest control + nutrition\n\n**Application Tips:**\n• Split N application for better efficiency\n• Apply P & K as basal dose before sowing\n• Don't over-fertilize - causes pollution & cost";
      }
      
      // Organic farming
      if (matchesKeyword(['organic', 'jaivik', 'natural', 'bio'])) {
        return "🌿 **Organic Farming Practices:**\n\n**Benefits:**\n✅ Better soil health & biodiversity\n✅ Higher market price (20-30% premium)\n✅ Safe for environment and health\n✅ Reduced input costs long-term\n\n**Key Practices:**\n• Crop rotation & intercropping\n• Green manuring (sunhemp, dhaincha)\n• Vermicomposting & FYM application\n• Biological pest control (Trichoderma, NPV)\n• Mulching & water conservation\n\n**Organic Inputs:**\n• Panchagavya for growth promotion\n• Neem oil for pest control\n• Jeevamrut for soil health\n• Beejamrut for seed treatment\n\n**Certification:** Contact local organic certification bodies";
      }
      
      // Pest management
      if (matchesKeyword(['pest', 'insect', 'bug', 'keeda', 'keet'])) {
        return "🐛 **Integrated Pest Management (IPM):**\n\n**Prevention First:**\n• Use disease-resistant varieties\n• Crop rotation breaks pest cycles\n• Maintain field sanitation\n• Proper spacing for air circulation\n\n**Monitoring:**\n• Install pheromone traps (1/acre)\n• Light traps for night-flying insects\n• Yellow sticky traps for whiteflies\n• Scout fields weekly\n\n**Biological Control:**\n• Trichogramma for bollworms\n• Chrysoperla for aphids\n• NPV viruses for caterpillars\n• Neem oil (5ml/liter) as natural repellent\n\n**Chemical Control (Last Resort):**\n• Use recommended doses only\n• Rotate pesticide groups to prevent resistance\n• Follow safety withdrawal periods before harvest";
      }
      
      // Disease management
      if (matchesKeyword(['disease', 'bimari', 'rog', 'infection', 'fungus', 'virus'])) {
        return "🦠 **Plant Disease Management:**\n\n**Common Diseases:**\n\n**Fungal:**\n• Blight (potato, tomato) - Use mancozeb\n• Rust (wheat, pulses) - Propiconazole spray\n• Powdery mildew - Sulfur dusting\n\n**Bacterial:**\n• Bacterial leaf spot - Copper fungicides\n• Wilt diseases - Crop rotation essential\n\n**Viral:**\n• Yellow mosaic - Control whitefly vectors\n• Leaf curl - Remove infected plants immediately\n\n**Prevention:**\n• Use certified disease-free seeds\n• Treat seeds with Trichoderma\n• Avoid over-watering and waterlogging\n• Remove crop residues after harvest\n• Maintain proper field hygiene\n\n**Use our Disease Detection feature to identify diseases!**";
      }
      
      // Weather
      if (matchesKeyword(['weather', 'mausam', 'climate', 'temperature', 'rain'])) {
        return "🌤️ **Weather & Crop Management:**\n\n**Temperature Impact:**\n• **High (>35°C):** Increases water need, affects pollination\n• **Low (<15°C):** Slows growth, frost damage risk\n• **Optimal:** Varies by crop - check specific guides\n\n**Rainfall Patterns:**\n• **Monsoon (June-Sep):** Kharif crops (rice, cotton, soybean)\n• **Winter (Oct-Mar):** Rabi crops (wheat, mustard, chickpea)\n• **Summer:** Irrigated crops only\n\n**Weather-Based Actions:**\n• Heavy rain forecast → Postpone spraying\n• Heat wave → Increase irrigation frequency\n• Cold wave → Protect seedlings with mulch\n• High humidity (>80%) → Monitor for fungal diseases\n\n**Check KisanConnect weather widget for:**\n• 7-day accurate forecasts\n• Agricultural advisories\n• Rainfall predictions";
      }
      
      // Irrigation
      if (matchesKeyword(['irrigation', 'water', 'pani', 'sikai', 'drip'])) {
        return "💧 **Smart Irrigation Practices:**\n\n**Methods:**\n• **Drip:** 40-70% water saving, best for vegetables, cotton\n• **Sprinkler:** Uniform coverage, good for wheat, vegetables\n• **Furrow:** Traditional, suitable for row crops\n• **Flood:** For rice paddies\n\n**Critical Stages for Irrigation:**\n• **Wheat:** Crown root, tillering, flowering, grain filling\n• **Rice:** Transplanting, tillering, flowering\n• **Cotton:** Square formation, flowering, boll development\n\n**Water Conservation:**\n• Mulching reduces evaporation by 50%\n• Irrigate in early morning or evening\n• Adopt micro-irrigation (govt subsidies available)\n• Rainwater harvesting in farm ponds\n\n**Water scheduling based on soil moisture is most efficient!**";
      }
      
      // Market prices
      if (matchesKeyword(['price', 'bhav', 'market', 'mandi', 'sell', 'bech'])) {
        return "💰 **Market Price Information:**\n\nTo get current market prices:\n1. Visit the **Market Analysis** section in KisanConnect\n2. Check live Mandi prices for your region\n3. Compare prices across different markets\n\n**Price Trends:**\n• Monitor 30-day price charts\n• Understand seasonal price variations\n• Plan harvesting based on price forecasts\n\n**Better Prices Tips:**\n• Grade your produce properly (A, B, C grades)\n• Clean and dry grains before selling\n• Join Farmer Producer Organizations (FPOs)\n• Use e-NAM platform for wider market access\n• Store produce when prices are low (if facilities available)\n• Direct selling to retailers can give 15-20% more";
      }
      
      // Government schemes
      if (matchesKeyword(['subsidy', 'scheme', 'yojana', 'government', 'sarkar', 'pm-kisan'])) {
        return "🎁 **Government Schemes & Subsidies:**\n\n**PM-KISAN:**\n• ₹6000/year direct benefit transfer\n• For all farmer families\n\n**Crop Insurance (PMFBY):**\n• 2% premium for Kharif crops\n• 1.5% for Rabi crops\n• Coverage against natural calamities\n\n**Irrigation Subsidy:**\n• 90% subsidy for SC/ST farmers on micro-irrigation\n• 80% for small/marginal farmers\n\n**Machinery Subsidy:**\n• 40-50% subsidy on farm equipment\n• Custom Hiring Centers for shared machinery\n\n**Soil Health Card:**\n• Free soil testing every 2 years\n• Nutrient-based recommendations\n\n**KCC (Kisan Credit Card):**\n• Easy farm loans at 4% interest\n• Up to ₹3 lakh without collateral";
      }
      
      // Crop rotation
      if (matchesKeyword(['rotation', 'chakra', 'cycle', 'alternate'])) {
        return "🔄 **Crop Rotation Benefits:**\n\n**Why Rotate:**\n✅ Prevents soil nutrient depletion\n✅ Breaks pest & disease cycles\n✅ Improves soil structure\n✅ Increases overall farm income\n✅ Reduces fertilizer dependency\n\n**Good Rotation Examples:**\n• **Rice → Wheat → Legume** (Punjab, Haryana)\n• **Cotton → Wheat → Green Gram** (Maharashtra)\n• **Soybean → Wheat → Summer Moong** (MP)\n• **Groundnut → Wheat → Fodder** (Gujarat)\n\n**Principles:**\n• Follow deep-rooted with shallow-rooted crops\n• Include legumes (add nitrogen naturally to soil)\n• Alternate high & low nutrient demand crops\n• Include green manure crops periodically\n\n**Never grow the same crop continuously in same field!**";
      }
      
      // Seasonal planning
      if (matchesKeyword(['season', 'kharif', 'rabi', 'zaid', 'calendar'])) {
        return "📅 **Crop Calendar & Seasonal Guide:**\n\n**Kharif (June-October) - Monsoon Season:**\n• Rice, cotton, soybean, maize\n• Groundnut, bajra, jowar, tur\n• Monsoon-dependent crops\n\n**Rabi (October-March) - Winter Season:**\n• Wheat, mustard, chickpea, barley\n• Potato, onion, peas\n• Requires irrigation\n\n**Summer/Zaid (March-June):**\n• Watermelon, cucumber, vegetables\n• Fodder crops, green gram (moong)\n• High water requirement\n\n**Perennial Crops:**\n• Sugarcane (12-18 months)\n• Fruit trees, coconut, spices\n\n**October 2025 Activities:**\n• Start wheat sowing in North India\n• Harvest Kharif crops (rice, cotton)\n• Prepare land for Rabi season\n• Apply basal fertilizers";
      }
    }
    
    // Hindi language responses (ALL WORDS PROPERLY TRANSLATED)
    if (language === 'hi') {
      // Greetings
      if (matchesKeyword(['hello', 'hi', 'hey', 'namaste', 'namaskar', 'नमस्ते', 'नमस्कार', 'हेलो', 'हाय'])) {
        return "🙏 नमस्ते! मैं आपका किसानकनेक्ट सहायक हूं। मैं आपकी इन चीज़ों में मदद कर सकता हूं:\n\n✅ फसल उगाने का मार्गदर्शन\n✅ कीट और रोग प्रबंधन\n✅ मिट्टी और उर्वरक सलाह\n✅ मौसम और सिंचाई सुझाव\n✅ बाजार भाव और रुझान\n✅ सरकारी योजनाएं\n\nआज खेती के बारे में क्या जानना चाहेंगे?";
      }
      
      // Help
      if (matchesKeyword(['help', 'मदद', 'सहायता', 'guide', 'बताओ', 'बताइए', 'क्या कर सकते हो'])) {
        return "🤝 **मैं आपकी कैसे मदद कर सकता हूं:**\n\n**मुझसे पूछें:**\n• विशेष फसलें (गेहूं, धान, कपास, इत्यादि)\n• मिट्टी परीक्षण और प्रबंधन\n• उर्वरक और जैविक खेती\n• कीट और रोग नियंत्रण\n• सिंचाई तकनीकें\n• बाजार भाव और बिक्री सुझाव\n• मौसम आधारित खेती\n• सरकारी योजनाएं और सब्सिडी\n• फसल चक्र और मौसमी योजना\n\n**उदाहरण प्रश्न:**\n• \"गेहूं कैसे उगाएं?\"\n• \"धान के लिए कौन सी खाद?\"\n• \"कपास बोने का सबसे अच्छा समय?\"\n• \"वर्तमान टमाटर भाव?\"\n• \"जैविक तरीके से कीट नियंत्रण कैसे करें?\"";
      }
      
      // Thanks
      if (matchesKeyword(['thank', 'thanks', 'धन्यवाद', 'शुक्रिया', 'appreciate'])) {
        return "🙏 आपका बहुत स्वागत है! मैं हमेशा मदद के लिए यहां हूं। याद रखें:\n\n💡 हमारा **मौसम विजेट** पूर्वानुमान के लिए देखें\n📊 भावों के लिए **बाजार विश्लेषण** पर जाएं\n🌾 व्यक्तिगत सुझावों के लिए **फसल सिफारिश** उपयोग करें\n📸 पौधों की समस्याओं की पहचान के लिए **रोग जांच** आज़माएं\n\nखुशहाल खेती! आपके खेत उपजाऊ हों और फसलें भरपूर हों! 🌾✨";
      }
      
      // Wheat
      if (matchesKeyword(['wheat', 'गेहूं', 'गहूं'])) {
        return "🌾 **गेहूं की खेती मार्गदर्शिका:**\n\n📅 **बुवाई का समय:** नवंबर-दिसंबर (रबी मौसम)\n🌡️ **तापमान:** 10-25°सेल्सियस उत्तम\n💧 **सिंचाई:** हर 20-25 दिन में, 4-6 सिंचाई जरूरी\n🧪 **मिट्टी पीएच:** 6.0-7.5 (हल्की अम्लीय से तटस्थ)\n🌱 **बीज दर:** 100-125 किलोग्राम प्रति हेक्टेयर\n🌿 **किस्में:** एचडी-2967, पीबीडब्ल्यू-343, डीबीडब्ल्यू-17\n💰 **अपेक्षित उपज:** 40-50 क्विंटल प्रति हेक्टेयर\n\n**महत्वपूर्ण सुझाव:**\n• बेहतर नाइट्रोजन उपयोग के लिए यूरिया को 3 बार में डालें\n• बुवाई के 30-35 दिन बाद खरपतवार नियंत्रित करें\n• रतुआ और माहू के हमले से सावधान रहें\n• पहली सिंचाई बुवाई के 20-25 दिन बाद करें";
      }
      
      // Rice
      if (matchesKeyword(['rice', 'धान', 'चावल', 'paddy', 'dhan'])) {
        return "🌾 **धान की खेती संपूर्ण मार्गदर्शिका:**\n\n📅 **मौसम:**\n• खरीफ (जून-जुलाई) - मुख्य मौसम\n• रबी (नवंबर-दिसंबर) - सर्दी का धान\n🌡️ **तापमान:** 20-35°सेल्सियस\n💧 **पानी:** खड़ा पानी चाहिए, 1200-1500 मिलीमीटर वर्षा\n🧪 **मिट्टी पीएच:** 5.5-6.5 (अम्लीय)\n🌱 **किस्में:** स्वर्णा, आईआर-64, बासमती\n💰 **उपज:** 50-60 क्विंटल प्रति हेक्टेयर\n\n**मुख्य बिंदु:**\n• पानी रोकने के लिए पडलिंग अनिवार्य\n• 25-30 दिन पुराने पौधे रोपें\n• पत्तियां पीली हों तो जिंक सल्फेट डालें\n• झुलसा और भूरे धब्बे रोगों से सावधान रहें\n• 2-3 इंच खड़ा पानी बनाए रखें";
      }
      
      // Cotton
      if (matchesKeyword(['cotton', 'कपास', 'रुई', 'kapas'])) {
        return "🌿 **कपास खेती की आवश्यक बातें:**\n\n📅 **बुवाई:** अप्रैल-मई (खरीफ)\n🌡️ **जलवायु:** गर्म 21-30°सेल्सियस, 180+ पाला रहित दिन\n💧 **वर्षा:** 50-100 सेंटीमीटर सालाना\n🧪 **मिट्टी:** काली कपास मिट्टी आदर्श (पीएच 6.5-8.0)\n🌱 **दूरी:** 90 सेंटीमीटर × 60 सेंटीमीटर\n💰 **उपज:** 15-20 क्विंटल प्रति हेक्टेयर\n\n**प्रबंधन:**\n• ड्रिप सिंचाई से 40% पानी की बचत\n• गुलाबी सुंडी प्रमुख कीट है - फेरोमोन जाल लगाएं\n• बीटी कपास सुंडी प्रतिरोध देता है\n• जब 60% टिंडे खुलें तब काटें\n• पहली तुड़ाई 120-130 दिन बाद";
      }
      
      // Sugarcane  
      if (matchesKeyword(['sugarcane', 'ganna', 'गन्ना', 'ईख'])) {
        return "🎋 **गन्ना की खेती:**\n\n📅 **रोपाई:** फरवरी-मार्च (वसंत), सितंबर-अक्टूबर (शरद)\n🌡️ **तापमान:** वृद्धि के दौरान 20-30°सेल्सियस\n💧 **पानी:** अधिक जरूरत - 1500-2500 मिलीमीटर\n🧪 **मिट्टी:** गहरी, अच्छी जल निकासी वाली दोमट (पीएच 6.5-7.5)\n🌱 **किस्में:** सीओ-0238, सीओ-86032, सीओ-0403\n💰 **उपज:** 800-1000 क्विंटल प्रति हेक्टेयर\n\n**देखभाल सुझाव:**\n• प्रति हेक्टेयर 300 किलोग्राम एन, 60 किलोग्राम पी, 60 किलोग्राम के डालें\n• 90-120 दिनों पर मिट्टी चढ़ाना महत्वपूर्ण\n• लाल सड़न और कंडुआ रोगों को नियंत्रित करें\n• 10-12 महीनों में कटाई करें\n• 2-3 मौसमों तक पेड़ी की फसल संभव";
      }
      
      // Maize
      if (matchesKeyword(['maize', 'corn', 'makka', 'मक्का', 'भुट्टा'])) {
        return "🌽 **मक्का उगाने की मार्गदर्शिका:**\n\n📅 **मौसम:** खरीफ (जून-जुलाई), रबी (अक्टूबर-नवंबर)\n🌡️ **तापमान:** 21-27°सेल्सियस आदर्श\n💧 **सिंचाई:** फूल आने और दाना भरने के समय महत्वपूर्ण\n🧪 **मिट्टी पीएच:** 5.5-7.5\n🌱 **दूरी:** 60 सेंटीमीटर × 20 सेंटीमीटर\n💰 **उपज:** 60-70 क्विंटल प्रति हेक्टेयर\n\n**सर्वोत्तम तरीके:**\n• बेहतर उपज के लिए संकर बीज का उपयोग करें\n• 120 किलोग्राम नाइट्रोजन को 3 बार में डालें\n• जैविक एजेंटों से फॉल आर्मीवर्म नियंत्रित करें\n• दाने सख्त होने पर कटाई करें\n• फफूंद रोकने के लिए उचित सुखाई जरूरी";
      }
      
      // Soybean
      if (matchesKeyword(['soybean', 'soya', 'सोयाबीन'])) {
        return "🫘 **सोयाबीन खेती के सुझाव:**\n\n📅 **बुवाई:** जून-जुलाई (मानसून के साथ)\n🌡️ **तापमान:** 20-30°सेल्सियस\n💧 **वर्षा:** 450-700 मिलीमीटर\n🧪 **मिट्टी:** अच्छी जल निकासी वाली दोमट (पीएच 6.5-7.5)\n🌱 **बीज दर:** 75-80 किलोग्राम प्रति हेक्टेयर\n💰 **उपज:** 20-25 क्विंटल प्रति हेक्टेयर\n\n**सफलता के सुझाव:**\n• बीजों को राइज़ोबियम बैक्टीरिया से उपचारित करें\n• 30-45 सेंटीमीटर पंक्ति दूरी पर बोएं\n• पीली मोज़ेक विषाणु नियंत्रित करें (प्रतिरोधी किस्में उपयोग करें)\n• जब 95% फलियां भूरी हो जाएं तब काटें\n• अच्छी चक्रीय फसल - मिट्टी में नाइट्रोजन जोड़ती है";
      }
      
      // Groundnut
      if (matchesKeyword(['groundnut', 'peanut', 'मूंगफली', 'singdana'])) {
        return "🥜 **मूंगफली की खेती:**\n\n📅 **मौसम:** खरीफ (जून) और गर्मी (जनवरी-फरवरी)\n🌡️ **तापमान:** 20-30°सेल्सियस\n💧 **पानी:** 500-600 मिलीमीटर सुवितरित\n🧪 **मिट्टी:** बलुई दोमट, लाल मिट्टी (पीएच 6.0-6.5)\n🌱 **किस्में:** टीएमवी-2, जेएल-24, टीएजी-24\n💰 **उपज:** 20-25 क्विंटल प्रति हेक्टेयर\n\n**महत्वपूर्ण सुझाव:**\n• फूल आने पर जिप्सम डालें (200-400 किलोग्राम प्रति हेक्टेयर)\n• फली विकास के लिए महत्वपूर्ण\n• पत्ती खनक और टिक्का रोग नियंत्रित करें\n• पत्तियां पीली होने पर कटाई करें\n• भंडारण से पहले धूप में 3-4 दिन सुखाएं";
      }
      
      // Soil
      if (matchesKeyword(['soil', 'मिट्टी', 'भूमि', 'जमीन', 'land'])) {
        return "🌱 **मिट्टी स्वास्थ्य प्रबंधन:**\n\n**मिट्टी परीक्षण:** एनपीके, पीएच, जैविक पदार्थ के लिए हर 2-3 साल में परीक्षण करें\n\n**मिट्टी के प्रकार और सर्वोत्तम फसलें:**\n• **काली मिट्टी:** कपास, सोयाबीन, गेहूं, ज्वार\n• **लाल मिट्टी:** मूंगफली, बाजरा, दालें\n• **जलोढ़ मिट्टी:** धान, गेहूं, गन्ना, सब्जियां\n• **बलुई मिट्टी:** बाजरा, मूंगफली, तरबूज\n• **लेटराइट मिट्टी:** काजू, नारियल, मसाले\n\n**सुधार के तरीके:**\n• जैविक पदार्थ मिलाएं (गोबर खाद 10-15 टन प्रति हेक्टेयर)\n• ढैंचा, सनई से हरी खाद\n• पोषक तत्व ह्रास रोकने के लिए फसल चक्र\n• नमी बनाए रखने के लिए मल्चिंग\n• अत्यधिक जुताई से बचें";
      }
      
      // Fertilizer
      if (matchesKeyword(['fertilizer', 'खाद', 'उर्वरक', 'npk', 'urea', 'यूरिया'])) {
        return "💊 **उर्वरक प्रयोग मार्गदर्शिका:**\n\n**प्रमुख पोषक तत्व (एनपीके):**\n• **नाइट्रोजन (एन):** पत्ती वृद्धि, हरापन - यूरिया, सीएएन\n• **फास्फोरस (पी):** जड़ विकास - डीएपी, एसएसपी\n• **पोटेशियम (के):** रोग प्रतिरोध - एमओपी, एसओपी\n\n**सूक्ष्म पोषक तत्व:**\n• **जिंक:** पीली पत्तियां, बौनापन रोकता है\n• **बोरॉन:** फूल आने, फल लगने के लिए जरूरी\n• **आयरन:** युवा पत्तियों में हरिमाहीनता रोकता है\n\n**जैविक विकल्प:**\n• गोबर खाद: 10-15 टन प्रति हेक्टेयर\n• वर्मीकम्पोस्ट: 2-3 टन प्रति हेक्टेयर\n• नीम खली: कीट नियंत्रण और पोषण\n\n**प्रयोग सुझाव:**\n• बेहतर दक्षता के लिए नाइट्रोजन विभाजित प्रयोग\n• बुवाई से पहले फास्फोरस और पोटेशियम आधार खुराक के रूप में\n• अधिक उर्वरक न डालें - प्रदूषण और लागत बढ़ती है";
      }
      
      // Organic
      if (matchesKeyword(['organic', 'जैविक', 'प्राकृतिक', 'natural'])) {
        return "🌿 **जैविक खेती के तरीके:**\n\n**लाभ:**\n✅ बेहतर मिट्टी स्वास्थ्य और जैव विविधता\n✅ अधिक बाजार मूल्य (20-30% अधिक)\n✅ पर्यावरण और स्वास्थ्य के लिए सुरक्षित\n✅ दीर्घकालिक में कम लागत\n\n**मुख्य तरीके:**\n• फसल चक्र और मिश्रित खेती\n• हरी खाद (सनई, ढैंचा)\n• वर्मीकम्पोस्टिंग और गोबर खाद प्रयोग\n• जैविक कीट नियंत्रण (ट्राइकोडर्मा, एनपीवी)\n• मल्चिंग और जल संरक्षण\n\n**जैविक सामग्री:**\n• पंचगव्य - वृद्धि बढ़ाने के लिए\n• नीम तेल - कीट नियंत्रण के लिए\n• जीवामृत - मिट्टी स्वास्थ्य के लिए\n• बीजामृत - बीज उपचार के लिए\n\n**प्रमाणन:** स्थानीय जैविक प्रमाणन संस्थाओं से संपर्क करें";
      }
      
      // Pest
      if (matchesKeyword(['pest', 'keet', 'कीट', 'कीड़े', 'insect', 'bug'])) {
        return "🐛 **एकीकृत कीट प्रबंधन:**\n\n**रोकथाम पहले:**\n• रोग प्रतिरोधी किस्में उपयोग करें\n• फसल चक्र कीट चक्र तोड़ता है\n• खेत स्वच्छता बनाए रखें\n• हवा संचार के लिए उचित दूरी\n\n**निगरानी:**\n• फेरोमोन जाल लगाएं (1 प्रति एकड़)\n• रात में उड़ने वाले कीड़ों के लिए प्रकाश जाल\n• सफेद मक्खियों के लिए पीले चिपचिपे जाल\n• साप्ताहिक खेत निरीक्षण करें\n\n**जैविक नियंत्रण:**\n• सुंडियों के लिए ट्राइकोग्रामा\n• माहू के लिए क्राइसोपर्ला\n• इल्लियों के लिए एनपीवी वायरस\n• प्राकृतिक प्रतिकर्षक के रूप में नीम तेल (5 मिलीलीटर प्रति लीटर)\n\n**रासायनिक नियंत्रण (अंतिम उपाय):**\n• केवल अनुशंसित खुराक उपयोग करें\n• प्रतिरोध रोकने के लिए कीटनाशक समूह बदलें\n• कटाई से पहले सुरक्षा अवधि का पालन करें";
      }
      
      // Disease
      if (matchesKeyword(['disease', 'बीमारी', 'रोग', 'infection', 'rog'])) {
        return "🦠 **पौधों के रोग प्रबंधन:**\n\n**सामान्य रोग:**\n\n**फफूंद रोग:**\n• झुलसा (आलू, टमाटर) - मैंकोज़ेब उपयोग करें\n• रतुआ (गेहूं, दालें) - प्रोपिकोनाज़ोल छिड़काव\n• चूर्णी फफूंद - गंधक धूलन\n\n**जीवाणु रोग:**\n• जीवाणु पत्ती धब्बा - तांबा फफूंदनाशक\n• उकठा रोग - फसल चक्र अनिवार्य\n\n**विषाणु रोग:**\n• पीली मोज़ेक - सफेद मक्खी वाहक नियंत्रित करें\n• पत्ती मोड़ - संक्रमित पौधे तुरंत हटाएं\n\n**रोकथाम:**\n• प्रमाणित रोग-मुक्त बीज उपयोग करें\n• बीजों को ट्राइकोडर्मा से उपचारित करें\n• अधिक पानी और जलभराव से बचें\n• कटाई के बाद फसल अवशेष हटाएं\n• उचित खेत स्वच्छता बनाए रखें\n\n**रोगों की पहचान के लिए हमारी रोग जांच सुविधा उपयोग करें!**";
      }
      
      // Weather
      if (matchesKeyword(['weather', 'मौसम', 'temperature', 'तापमान', 'बारिश', 'rain', 'climate'])) {
        return "🌤️ **मौसम और फसल प्रबंधन:**\n\n**तापमान प्रभाव:**\n• **उच्च (>35°सेल्सियस):** पानी की जरूरत बढ़ती है, परागण प्रभावित होता है\n• **कम (<15°सेल्सियस):** वृद्धि धीमी होती है, पाला क्षति का खतरा\n• **उत्तम:** फसल के अनुसार भिन्न - विशेष मार्गदर्शिका देखें\n\n**वर्षा पैटर्न:**\n• **मानसून (जून-सितंबर):** खरीफ फसलें (धान, कपास, सोयाबीन)\n• **सर्दी (अक्टूबर-मार्च):** रबी फसलें (गेहूं, सरसों, चना)\n• **गर्मी:** केवल सिंचित फसलें\n\n**मौसम आधारित कार्य:**\n• भारी बारिश पूर्वानुमान → छिड़काव स्थगित करें\n• लू → सिंचाई आवृत्ति बढ़ाएं\n• शीत लहर → मल्च से पौध सुरक्षा करें\n• उच्च आर्द्रता (>80%) → फफूंद रोगों की निगरानी करें\n\n**इन चीज़ों के लिए किसानकनेक्ट मौसम विजेट देखें:**\n• 7-दिन सटीक पूर्वानुमान\n• कृषि सलाह\n• वर्षा भविष्यवाणी";
      }
      
      // Irrigation  
      if (matchesKeyword(['irrigation', 'सिंचाई', 'water', 'पानी', 'drip', 'सींचना'])) {
        return "💧 **स्मार्ट सिंचाई तरीके:**\n\n**विधियां:**\n• **ड्रिप:** 40-70% पानी बचत, सब्जियों, कपास के लिए सर्वोत्तम\n• **फव्वारा:** समान कवरेज, गेहूं, सब्जियों के लिए अच्छा\n• **नाली:** पारंपरिक, पंक्ति फसलों के लिए उपयुक्त\n• **बाढ़:** धान की क्यारियों के लिए\n\n**सिंचाई के महत्वपूर्ण चरण:**\n• **गेहूं:** मूल जड़, कल्ले फूटना, फूल आना, दाना भरना\n• **धान:** रोपाई, कल्ले फूटना, फूल आना\n• **कपास:** टिंडा बनना, फूल आना, टिंडा विकास\n\n**जल संरक्षण:**\n• मल्चिंग से 50% वाष्पीकरण कम होता है\n• सुबह या शाम को सिंचाई करें\n• सूक्ष्म सिंचाई अपनाएं (सरकारी सब्सिडी उपलब्ध)\n• खेत तालाबों में वर्षा जल संचय\n\n**मिट्टी की नमी आधारित जल समय-निर्धारण सबसे कुशल है!**";
      }
      
      // Market
      if (matchesKeyword(['price', 'भाव', 'market', 'मंडी', 'बाजार', 'sell', 'बेचना'])) {
        return "💰 **बाजार मूल्य जानकारी:**\n\nवर्तमान बाजार मूल्य प्राप्त करने के लिए:\n1. किसानकनेक्ट में **बाजार विश्लेषण** अनुभाग पर जाएं\n2. अपने क्षेत्र के लिए लाइव मंडी भाव देखें\n3. विभिन्न बाजारों में मूल्यों की तुलना करें\n\n**मूल्य रुझान:**\n• 30-दिवसीय मूल्य चार्ट देखें\n• मौसमी मूल्य परिवर्तन समझें\n• मूल्य पूर्वानुमान के आधार पर कटाई की योजना बनाएं\n\n**बेहतर मूल्य के सुझाव:**\n• अपनी उपज को ठीक से श्रेणीबद्ध करें (ए, बी, सी श्रेणियां)\n• बिक्री से पहले अनाज साफ और सूखा करें\n• किसान उत्पादक संगठनों में शामिल हों\n• व्यापक बाजार पहुंच के लिए ई-नाम मंच उपयोग करें\n• मूल्य कम होने पर उपज भंडारित करें (यदि सुविधा उपलब्ध हो)\n• खुदरा विक्रेताओं को सीधी बिक्री से 15-20% अधिक मिल सकता है";
      }
      
      // Government
      if (matchesKeyword(['subsidy', 'सब्सिडी', 'scheme', 'योजना', 'government', 'सरकार', 'pm-kisan', 'yojana'])) {
        return "🎁 **सरकारी योजनाएं और सब्सिडी:**\n\n**पीएम-किसान:**\n• प्रति वर्ष ₹6000 सीधा लाभ हस्तांतरण\n• सभी किसान परिवारों के लिए\n\n**फसल बीमा (पीएमएफबीवाई):**\n• खरीफ फसलों के लिए 2% प्रीमियम\n• रबी फसलों के लिए 1.5%\n• प्राकृतिक आपदाओं के खिलाफ कवरेज\n\n**सिंचाई सब्सिडी:**\n• सूक्ष्म सिंचाई पर अनुसूचित जाति/जनजाति किसानों के लिए 90% सब्सिडी\n• छोटे/सीमांत किसानों के लिए 80%\n\n**मशीनरी सब्सिडी:**\n• कृषि उपकरण पर 40-50% सब्सिडी\n• साझा मशीनरी के लिए कस्टम हायरिंग केंद्र\n\n**मृदा स्वास्थ्य कार्ड:**\n• हर 2 साल में मुफ्त मिट्टी परीक्षण\n• पोषक तत्व आधारित सिफारिशें\n\n**केसीसी (किसान क्रेडिट कार्ड):**\n• 4% ब्याज पर आसान कृषि ऋण\n• बिना गिरवी के ₹3 लाख तक";
      }
      
      // Rotation
      if (matchesKeyword(['rotation', 'चक्र', 'फसल चक्र', 'chakra'])) {
        return "🔄 **फसल चक्र के लाभ:**\n\n**चक्र क्यों करें:**\n✅ मिट्टी में पोषक तत्व कमी रोकता है\n✅ कीट और रोग चक्र तोड़ता है\n✅ मिट्टी संरचना सुधारता है\n✅ कुल कृषि आय बढ़ाता है\n✅ उर्वरक निर्भरता कम करता है\n\n**अच्छे चक्र के उदाहरण:**\n• **धान → गेहूं → दलहन** (पंजाब, हरियाणा)\n• **कपास → गेहूं → हरा चना** (महाराष्ट्र)\n• **सोयाबीन → गेहूं → गर्मी मूंग** (मध्य प्रदेश)\n• **मूंगफली → गेहूं → चारा** (गुजरात)\n\n**सिद्धांत:**\n• गहरी जड़ वाली फसलों के बाद उथली जड़ वाली फसलें लें\n• दलहन शामिल करें (मिट्टी में प्राकृतिक रूप से नाइट्रोजन जोड़ती हैं)\n• उच्च और कम पोषक मांग वाली फसलें बारी-बारी से लें\n• समय-समय पर हरी खाद फसलें शामिल करें\n\n**एक ही खेत में लगातार एक ही फसल कभी न उगाएं!**";
      }
      
      // Seasonal
      if (matchesKeyword(['season', 'मौसम', 'kharif', 'rabi', 'खरीफ', 'रबी', 'zaid', 'जायद'])) {
        return "📅 **फसल कैलेंडर और मौसमी मार्गदर्शिका:**\n\n**खरीफ (जून-अक्टूबर) - मानसून मौसम:**\n• धान, कपास, सोयाबीन, मक्का\n• मूंगफली, बाजरा, ज्वार, तुअर\n• मानसून पर निर्भर फसलें\n\n**रबी (अक्टूबर-मार्च) - सर्दी का मौसम:**\n• गेहूं, सरसों, चना, जौ\n• आलू, प्याज, मटर\n• सिंचाई की आवश्यकता\n\n**गर्मी/जायद (मार्च-जून):**\n• तरबूज, खीरा, सब्जियां\n• चारा फसलें, हरा चना (मूंग)\n• उच्च पानी आवश्यकता\n\n**बारहमासी फसलें:**\n• गन्ना (12-18 महीने)\n• फलों के पेड़, नारियल, मसाले\n\n**अक्टूबर 2025 गतिविधियां:**\n• उत्तर भारत में गेहूं बुवाई शुरू करें\n• खरीफ फसलों की कटाई करें (धान, कपास)\n• रबी मौसम के लिए जमीन तैयार करें\n• आधार उर्वरक डालें";
      }
    }
    
    // For all other languages, provide helpful multilingual responses
    const multilingualHelp = {
      'en': "I understand you're asking about farming. Could you be more specific? For example:\n\n• Specific crops: \"How to grow wheat?\"\n• Soil: \"How to improve soil health?\"\n• Pests: \"How to control pests?\"\n• Market: \"Current crop prices?\"\n• Weather: \"Irrigation tips?\"\n• Schemes: \"Tell me about PM-KISAN\"\n\nYou can ask in Hindi or other Indian languages!\n\nI'm here to help with all your farming questions! 🌾",
      'hi': "मुझे समझ आ रहा है कि आप खेती के बारे में पूछ रहे हैं। कृपया और स्पष्ट बताएं:\n\n• फसल: \"गेहूं कैसे उगाएं?\"\n• मिट्टी: \"मिट्टी स्वास्थ्य कैसे सुधारें?\"\n• कीट: \"कीट नियंत्रण कैसे करें?\"\n• बाजार: \"वर्तमान फसल भाव?\"\n• मौसम: \"सिंचाई सुझाव?\"\n• योजना: \"पीएम-किसान के बारे में बताएं\"\n\nआप हिंदी या अन्य भारतीय भाषाओं में पूछ सकते हैं!\n\nमैं आपके सभी खेती प्रश्नों में मदद के लिए हूं! 🌾",
      'mr': "मला समजले की तुम्ही शेतीबद्दल विचारत आहात। कृपया अधिक स्पष्टपणे सांगा:\n\n• पीक: \"गहू कसा पिकवायचा?\"\n• माती: \"माती आरोग्य कसे सुधारावे?\"\n• किड: \"किडींचे नियंत्रण कसे करावे?\"\n• बाजार: \"सध्याचे पीक भाव?\"\n• हवामान: \"सिंचनाचे सल्ले?\"\n\nमी तुमच्या सर्व शेती प्रश्नांसाठी येथे आहे! 🌾",
      'gu': "હું સમજી શકું છું કે તમે ખેતી વિશે પૂછી રહ્યા છો। કૃપા કરીને વધુ સ્પષ્ટ બોલો:\n\n• પાક: \"ઘઉં કેવી રીતે ઉગાડવું?\"\n• માટી: \"માટી આરોગ્ય કેવી રીતે સુધારવું?\"\n• જંતુ: \"જંતુ નિયંત્રણ કેવી રીતે કરવું?\"\n• બજાર: \"વર્તમાન પાક ભાવ?\"\n• હવામાન: \"સિંચાઈ સૂચનો?\"\n\nહું તમારા તમામ ખેતી પ્રશ્નોમાં મદદ માટે અહીં છું! 🌾",
      'pa': "ਮੈਂ ਸਮਝ ਸਕਦਾ ਹਾਂ ਕਿ ਤੁਸੀਂ ਖੇਤੀ ਬਾਰੇ ਪੁੱਛ ਰਹੇ ਹੋ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਸਪੱਸ਼ਟ ਦੱਸੋ:\n\n• ਫਸਲ: \"ਕਣਕ ਕਿਵੇਂ ਉਗਾਉਣੀ ਹੈ?\"\n• ਮਿੱਟੀ: \"ਮਿੱਟੀ ਸਿਹਤ ਕਿਵੇਂ ਸੁਧਾਰਨੀ ਹੈ?\"\n• ਕੀੜੇ: \"ਕੀੜੇ ਕਿਵੇਂ ਕੰਟਰੋਲ ਕਰਨੇ ਹਨ?\"\n• ਬਾਜ਼ਾਰ: \"ਮੌਜੂਦਾ ਫਸਲ ਭਾਅ?\"\n• ਮੌਸਮ: \"ਸਿੰਚਾਈ ਸੁਝਾਅ?\"\n\nਮੈਂ ਤੁਹਾਡੇ ਸਾਰੇ ਖੇਤੀ ਸਵਾਲਾਂ ਵਿੱਚ ਮਦਦ ਲਈ ਹਾਂ! 🌾",
      'bn': "আমি বুঝতে পারছি আপনি কৃষি সম্পর্কে জিজ্ঞাসা করছেন। আরও স্পষ্ট করে বলুন:\n\n• ফসল: \"গম কীভাবে চাষ করবেন?\"\n• মাটি: \"মাটির স্বাস্থ্য কীভাবে উন্নত করবেন?\"\n• পোকা: \"পোকা নিয়ন্ত্রণ কীভাবে করবেন?\"\n• বাজার: \"বর্তমান ফসলের দাম?\"\n• আবহাওয়া: \"সেচের পরামর্শ?\"\n\nআমি আপনার সমস্ত কৃষি প্রশ্নে সাহায্যের জন্য আছি! 🌾",
      'ta': "நீங்கள் விவசாயம் பற்றி கேட்கிறீர்கள் என்று புரிகிறது। தயவுசெய்து மேலும் தெளிவாகக் கூறுங்கள்:\n\n• பயிர்: \"கோதுமை எப்படி வளர்க்கலாம்?\"\n• மண்: \"மண் ஆரோக்கியத்தை எப்படி மேம்படுத்துவது?\"\n• பூச்சி: \"பூச்சி கட்டுப்பாடு எப்படி செய்வது?\"\n• சந்தை: \"தற்போதைய பயிர் விலை?\"\n• வானிலை: \"நீர்ப்பாசன ஆலோசனைகள்?\"\n\nஉங்கள் அனைத்து விவசாய கேள்விகளுக்கும் நான் உதவ இங்கே இருக்கிறேன்! 🌾",
      'te': "మీరు వ్యవసాయం గురించి అడుగుతున్నారని నాకు అర్థమైంది। దయచేసి మరింత స్పష్టంగా చెప్పండి:\n\n• పంట: \"గోధుమలు ఎలా పండించాలి?\"\n• నేల: \"నేల ఆరోగ్యం ఎలా మెరుగుపర్చాలి?\"\n• పురుగులు: \"పురుగుల నియంత్రణ ఎలా చేయాలి?\"\n• మార్కెట్: \"ప్రస్తుత పంట ధరలు?\"\n• వాతావరణం: \"నీటిపారుదల సలహాలు?\"\n\nనేను మీ అన్ని వ్యవసాయ ప్రశ్నలకు సహాయం చేయడానికి ఇక్కడ ఉన్నాను! 🌾"
    };
    
    return multilingualHelp[language] || multilingualHelp['en'];
  }
};
